// Code generated by bpf2go; DO NOT EDIT.

package containerlab

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfcapMapEvents            = "events"
	bpfcapProgTcCaptureEgress  = "tc_capture_egress"
	bpfcapProgTcCaptureIngress = "tc_capture_ingress"
)

// loadBpfcap returns the embedded CollectionSpec for bpfcap.
func loadBpfcap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfcapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfcap: %w", err)
	}

	return spec, err
}

// loadBpfcapObjects loads bpfcap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfcapObjects
//	*bpfcapPrograms
//	*bpfcapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfcapObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfcap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfcapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfcapSpecs struct {
	bpfcapProgramSpecs
	bpfcapMapSpecs
	bpfcapVariableSpecs
}

// bpfcapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfcapProgramSpecs struct {
	TcCaptureEgress  *ebpf.ProgramSpec `ebpf:"tc_capture_egress"`
	TcCaptureIngress *ebpf.ProgramSpec `ebpf:"tc_capture_ingress"`
}

// bpfcapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfcapMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// bpfcapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfcapVariableSpecs struct {
}

// bpfcapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfcapObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfcapObjects struct {
	bpfcapPrograms
	bpfcapMaps
	bpfcapVariables
}

func (o *bpfcapObjects) Close() error {
	return _BpfcapClose(
		&o.bpfcapPrograms,
		&o.bpfcapMaps,
	)
}

// bpfcapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfcapObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfcapMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *bpfcapMaps) Close() error {
	return _BpfcapClose(
		m.Events,
	)
}

// bpfcapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfcapObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfcapVariables struct {
}

// bpfcapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfcapObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfcapPrograms struct {
	TcCaptureEgress  *ebpf.Program `ebpf:"tc_capture_egress"`
	TcCaptureIngress *ebpf.Program `ebpf:"tc_capture_ingress"`
}

func (p *bpfcapPrograms) Close() error {
	return _BpfcapClose(
		p.TcCaptureEgress,
		p.TcCaptureIngress,
	)
}

func _BpfcapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfcap_bpf.o
var _BpfcapBytes []byte
